CREATE TABLE `order_info`
(
  `ORDER_SSN`             varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '支付内部订单号(1位8+14位yyyyMMddHHmmss+17位随机数)',
  `ORDER_TM`              datetime                        NOT NULL COMMENT '内部订单时间',
  `ORIG_ORDER_SSN`        varchar(32) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '原内部订单号(1位8+14位yyyyMMddHHmmss+17位随机数)',
  `ORIG_ORDER_TM`         datetime                          DEFAULT NULL COMMENT '原内部订单时间',
  `REQ_ORDER_SSN`         varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '请求订单号',
  `REQ_ORDER_TM`          datetime                        NOT NULL COMMENT '请求订单时间',
  `APP_SER_ID`            char(2) COLLATE utf8mb4_bin       DEFAULT NULL COMMENT '系统内部应用编号',
  `TXN_TYPE_NO`           char(10) COLLATE utf8mb4_bin    NOT NULL COMMENT '交易类型编号',
  `PROD_ID`               char(4) COLLATE utf8mb4_bin       DEFAULT NULL,
  `MEM_ID`                varchar(19) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '会员ID',
  `USER_ID`               varchar(19) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '用户编号',
  `MCHT_ID`               char(15) COLLATE utf8mb4_bin      DEFAULT NULL COMMENT '商户编号',
  `PRE_ROOM_NUM`          varchar(20) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '预授权房间号',
  `AUTH_TYPE`             char(2) COLLATE utf8mb4_bin       DEFAULT NULL,
  `AUTH_SEQ_NO`           varchar(32) COLLATE utf8mb4_bin   DEFAULT NULL,
  `AUTH_INFO`             varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL,
  `ORDER_DESC`            varchar(128) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '订单描述',
  `ORDER_REMARK`          varchar(128) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '拒绝理由',
  `ORDER_EXP_TM`          char(14) COLLATE utf8mb4_bin      DEFAULT NULL COMMENT '订单失效时间(格式：yyyyMMddHHmmss)',
  `TXN_AMT`               varchar(12) COLLATE utf8mb4_bin NOT NULL COMMENT '订单总金额(单位分，如：1.23元=123)',
  `PAY_AMT`               varchar(12) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '交易实付金额(单位分，如：1.23元=123)',
  `TXN_RFD_AMT_SUM`       varchar(12) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '订单剩余可退款金额,以分为单位，例:1.23元=123',
  `TXN_RFD_COUNT_SUM`     varchar(12) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '订单剩余可退款次数',
  `PAGY_TXN_SSN`          varchar(32) COLLATE utf8mb4_bin   DEFAULT NULL,
  `PAGY_TXN_TM`           datetime                          DEFAULT NULL,
  `TPAM_ORDER_SSN`        varchar(32) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '第三方通道订单号',
  `TPAM_ORDER_TM`         datetime                          DEFAULT NULL COMMENT '第三方通道订单时间',
  `PAGY_RESP_CODE`        char(4) COLLATE utf8mb4_bin       DEFAULT NULL COMMENT '通道支付响应码',
  `PAGY_RESP_MSG`         varchar(500) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '通道支付响应信息',
  `ORDER_STATE`           char(2) COLLATE utf8mb4_bin     NOT NULL COMMENT '订单状态：00=订单成功；01=已撤销；02=已发生退款；03=已关闭；09=订单失败；10=订单已受理；11=订单处理中；12= 用户输密中;13=订单处理超时；',
  `SYS_TRACE_ID`          varchar(32) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '系统跟踪号',
  `CRT_TM`                datetime                        NOT NULL COMMENT '创建时间',
  `UP_TM`                 datetime                          DEFAULT NULL COMMENT '修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_bin;